### ISSUE TITLE
google map with location marked, address section on faq page

### ISSUE THREAD

**Issue by heybornfire** [heybornfire/persistenceEducation#2]
I want someone to add address page at bottom and above a google map showing exact location,
For location search: persistence Education Ranchi,
address:
Persistence Educaation Pvt Ltd

Near Governor's House

Kalibabu street, Ranchi

Jharkhand - 834001

India

7488408051

8235071441

persistenceranchi@gmail.com

**Comment by imkks** [comment]
Please assign this issue also to me.
